

services:
   backend:
     build:
        context: .
        dockerfile: apps/http-backend/Dockerfile
     ports:
       - "8000:8000"
     environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECERT=${JWT_SECERT}
     networks:
      - sword-draw
     restart: unless-stopped
   websocket:
    build:
      context: .
      dockerfile: apps/ws-backend/Dockerfile
    ports:
     - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECERT=${JWT_SECERT}
    networks:
      - sword-draw
    restart: unless-stopped

   frontend:
    build:
      context: .
      dockerfile: apps/web-forntend/Dockerfile
    ports:
     - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000  
      - NEXT_PUBLIC_WEBSOCKET_URL=ws://localhost:8080
    depends_on:
      - backend
      - websocket
    networks:
     - sword-draw 
    restart: unless-stopped

networks:
  sword-draw:
    driver: bridge